- hosts: all
  become: yes
  remote_user: root
  gather_facts: yes
  vars_files:
    - ../vars.yml
    - ../secrets.yml

  tasks:
    - name: Restart the host
      shell: sleep 2 && /sbin/shutdown -r now "Ansible restart host"
      # This seems to not work with ansible >= 2.0
      # https://github.com/ansible/ansible/issues/14413
      # command: shutdown -r now "Ansible restart host"
      # async: 0
      # poll: 0
      ignore_errors: true

    - name: Wait for server to come back online
      local_action: wait_for host={{ ansible_eth0["ipv4"]["address"] }} port=22 state=started delay=30 timeout=60
      become: false
