- hosts: all
  become: yes
  remote_user: root
  gather_facts: yes
  vars_files:
    - ../vars.yml
    - ../secrets.yml

  tasks:
    - name: Install system dependencies
      apt: name={{ item }} state=present
      with_items:
        - aptitude
        - vim
        - git
        - tar
        - unzip
      when: >
        ansible_distribution == 'Debian'
        or
        ansible_distribution == 'Ubuntu'
