---

- hosts: all
  become: yes
  remote_user: root
  gather_facts: yes
  vars_files:
    - ../vars.yml
    - ../secrets.yml

  tasks:
    - name: Update apt repository and perform a full upgrade.
      apt: >
        update_cache=yes
        cache_valid_time=1200
        upgrade=full
      when: >
        ansible_distribution == 'Debian'
        or
        ansible_distribution == 'Ubuntu'

- handlers:
  - include: ../handlers/common.yml
